# Generated by Django 5.0.1 on 2025-11-09 05:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('width', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('height', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('tile_size', models.IntegerField(default=50, help_text='Size of each tile in pixels', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)])),
                ('map_type', models.CharField(choices=[('urban', 'Urban'), ('wilderness', 'Wilderness'), ('corporate', 'Corporate Facility'), ('underground', 'Underground/Sewer'), ('mixed', 'Mixed Environment')], default='urban', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Make this map visible to all players')),
                ('is_generated', models.BooleanField(default=False, help_text='Was this map procedurally generated?')),
                ('generation_seed', models.CharField(blank=True, help_text='Seed used for map generation (for reproducibility)', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Specific users who can view this map', related_name='shared_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MapGenerationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('width', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('height', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('map_type', models.CharField(choices=[('urban', 'Urban'), ('wilderness', 'Wilderness'), ('corporate', 'Corporate Facility'), ('underground', 'Underground/Sewer'), ('mixed', 'Mixed Environment')], default='urban', max_length=20)),
                ('obstacle_density', models.IntegerField(default=20, help_text='Percentage of tiles that are obstacles', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('object_density', models.IntegerField(default=10, help_text='Percentage of tiles that contain objects', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('generation_algorithm', models.CharField(default='random', help_text="Algorithm to use for generation (e.g., 'random', 'cellular_automata', 'bsp')", max_length=50)),
                ('custom_parameters', models.JSONField(blank=True, default=dict, help_text='Additional custom parameters for generation')),
                ('is_public', models.BooleanField(default=False, help_text='Make this preset available to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(choices=[('npc', 'NPC'), ('enemy', 'Enemy'), ('item', 'Item'), ('objective', 'Objective Marker'), ('trap', 'Trap'), ('entrance', 'Entrance/Exit'), ('cover', 'Cover'), ('vehicle', 'Vehicle'), ('marker', 'Custom Marker')], default='marker', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or emoji for the object', max_length=50)),
                ('color', models.CharField(default='#FF0000', help_text='Hex color code for the object', max_length=7)),
                ('is_visible_to_players', models.BooleanField(default=True, help_text='Is this object visible to players?')),
                ('blocks_movement', models.BooleanField(default=False)),
                ('blocks_vision', models.BooleanField(default=False)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Custom stats/properties (HP, damage, etc.)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='maps.map')),
            ],
            options={
                'ordering': ['y', 'x', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('terrain_type', models.CharField(choices=[('street', 'Street'), ('sidewalk', 'Sidewalk'), ('building', 'Building'), ('alley', 'Alley'), ('parking', 'Parking Lot'), ('grass', 'Grass'), ('forest', 'Forest'), ('water', 'Water'), ('mountain', 'Mountain'), ('desert', 'Desert'), ('floor', 'Floor'), ('wall', 'Wall'), ('door', 'Door'), ('window', 'Window'), ('stairs', 'Stairs'), ('elevator', 'Elevator'), ('tunnel', 'Tunnel'), ('sewer', 'Sewer'), ('cave', 'Cave'), ('void', 'Void'), ('custom', 'Custom')], default='floor', max_length=20)),
                ('is_walkable', models.BooleanField(default=True)),
                ('is_transparent', models.BooleanField(default=True, help_text='Can players see through this tile?')),
                ('color', models.CharField(default='#CCCCCC', help_text='Hex color code for the tile', max_length=7)),
                ('movement_cost', models.IntegerField(default=1, help_text='How many movement points to cross this tile', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('custom_properties', models.JSONField(blank=True, default=dict, help_text='Custom JSON properties for this tile')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='maps.map')),
            ],
            options={
                'ordering': ['y', 'x'],
                'unique_together': {('map', 'x', 'y')},
            },
        ),
    ]
