# Generated by Django 5.0.1 on 2025-11-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_alter_mapobject_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='fog_of_war_enabled',
            field=models.BooleanField(default=False, help_text='Enable fog of war for this map'),
        ),
        migrations.AddField(
            model_name='map',
            name='revealed_tiles',
            field=models.JSONField(blank=True, default=list, help_text='List of revealed tile coordinates [[x, y], ...] for fog of war'),
        ),
    ]
