# Generated by Django 5.0.1 on 2025-11-12 20:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0002_adeptpower_complexform_skill_spell_character_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this roll was made')),
                ('description', models.CharField(blank=True, help_text="Description of what this roll is for (e.g., 'Perception Check', 'Pistols Attack')", max_length=200)),
                ('pool_size', models.IntegerField(help_text='Number of dice in the pool', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('threshold', models.IntegerField(blank=True, help_text='Number of hits needed to succeed (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('use_rule_of_six', models.BooleanField(default=True, help_text='If True, 6s explode and add additional dice')),
                ('edge_used', models.BooleanField(default=False, help_text='Whether Edge was used on this roll')),
                ('dice_results', models.TextField(help_text="Comma-separated list of individual die results (e.g., '5,3,6,1,4')")),
                ('total_hits', models.IntegerField(default=0, help_text='Number of hits rolled (5s and 6s)')),
                ('ones_count', models.IntegerField(default=0, help_text='Number of 1s rolled (for glitch detection)')),
                ('is_glitch', models.BooleanField(default=False, help_text='True if more than half the dice showed 1')),
                ('is_critical_glitch', models.BooleanField(default=False, help_text='True if glitch occurred with zero hits')),
                ('success', models.BooleanField(blank=True, help_text='Whether the roll succeeded (null if no threshold set)', null=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaign this roll belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dice_rolls', to='campaigns.campaign')),
                ('character', models.ForeignKey(blank=True, help_text='Character making this roll (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dice_rolls', to='characters.character')),
                ('session', models.ForeignKey(blank=True, help_text='Session this roll belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dice_rolls', to='campaigns.session')),
                ('user', models.ForeignKey(help_text='User who made this roll', on_delete=django.db.models.deletion.CASCADE, related_name='dice_rolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dice Roll',
                'verbose_name_plural': 'Dice Rolls',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DicePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this preset (e.g., 'Combat Pool', 'Perception Check')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of when to use this preset')),
                ('pool_size', models.IntegerField(help_text='Default number of dice in the pool', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('threshold', models.IntegerField(blank=True, help_text='Default threshold (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('use_rule_of_six', models.BooleanField(default=True, help_text='Whether to use Rule of Six by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, help_text='Character this preset is associated with (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dice_presets', to='characters.character')),
                ('user', models.ForeignKey(help_text='User who created this preset', on_delete=django.db.models.deletion.CASCADE, related_name='dice_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dice Preset',
                'verbose_name_plural': 'Dice Presets',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
