# Generated by Django 5.0.1 on 2025-11-04 09:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('cyberware', 'Cyberware'), ('bioware', 'Bioware'), ('electronics', 'Electronics'), ('magical', 'Magical Equipment'), ('vehicle', 'Vehicle'), ('misc', 'Miscellaneous')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.IntegerField(help_text='Cost in nuyen')),
                ('availability', models.CharField(blank=True, max_length=10)),
                ('essence_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_default', models.BooleanField(default=True, help_text='Available in base catalog')),
            ],
            options={
                'verbose_name_plural': 'Gear',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('karma_cost', models.IntegerField(help_text='Karma cost (negative for positive qualities)')),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=True, help_text='Available for all characters')),
            ],
            options={
                'verbose_name_plural': 'Qualities',
                'ordering': ['quality_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('human', 'Human'), ('dwarf', 'Dwarf'), ('elf', 'Elf'), ('ork', 'Ork'), ('troll', 'Troll')], max_length=20)),
                ('archetype', models.CharField(choices=[('adept', 'Adept'), ('combat_mage', 'Combat Mage'), ('covert_ops', 'Covert Ops Specialist'), ('decker', 'Decker'), ('face', 'Face'), ('rigger', 'Rigger'), ('street_samurai', 'Street Samurai'), ('street_shaman', 'Street Shaman'), ('technomancer', 'Technomancer'), ('weapon_specialist', 'Weapon Specialist')], max_length=30)),
                ('role', models.CharField(choices=[('arcane_specialist', 'Arcane Specialist'), ('face', 'Face'), ('street_samurai', 'Street Samurai'), ('technology_specialist', 'Technology Specialist')], max_length=30)),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('raised_location', models.CharField(blank=True, max_length=200)),
                ('trained_location', models.CharField(blank=True, max_length=200)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('dark_aspects_feeling', models.TextField(blank=True, help_text='How character feels about darker aspects of the world')),
                ('wetwork_attitude', models.TextField(blank=True, help_text="Character's attitude toward wetwork")),
                ('background', models.TextField(blank=True, help_text='Character background and history')),
                ('metatype_priority', models.CharField(choices=[('A', 'A (Highest)'), ('B', 'B (High)'), ('C', 'C (Medium)'), ('D', 'D (Low)'), ('E', 'E (Lowest)')], default='C', max_length=1)),
                ('attributes_priority', models.CharField(choices=[('A', 'A (Highest)'), ('B', 'B (High)'), ('C', 'C (Medium)'), ('D', 'D (Low)'), ('E', 'E (Lowest)')], default='C', max_length=1)),
                ('magic_priority', models.CharField(choices=[('A', 'A (Highest)'), ('B', 'B (High)'), ('C', 'C (Medium)'), ('D', 'D (Low)'), ('E', 'E (Lowest)')], default='C', max_length=1)),
                ('skills_priority', models.CharField(choices=[('A', 'A (Highest)'), ('B', 'B (High)'), ('C', 'C (Medium)'), ('D', 'D (Low)'), ('E', 'E (Lowest)')], default='C', max_length=1)),
                ('resources_priority', models.CharField(choices=[('A', 'A (Highest)'), ('B', 'B (High)'), ('C', 'C (Medium)'), ('D', 'D (Low)'), ('E', 'E (Lowest)')], default='C', max_length=1)),
                ('body', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('agility', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reaction', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('strength', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('charisma', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('intuition', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('logic', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('willpower', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('edge', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('essence', models.DecimalField(decimal_places=2, default=6.0, max_digits=3)),
                ('magic', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('resonance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('starting_resources', models.IntegerField(default=0)),
                ('current_resources', models.IntegerField(default=0)),
                ('karma_total', models.IntegerField(default=0)),
                ('karma_spent', models.IntegerField(default=0)),
                ('karma_available', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False, help_text='Character creation completed')),
                ('creation_step', models.IntegerField(default=1, help_text='Current step in character creation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='characters.character')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.gear')),
            ],
            options={
                'unique_together': {('character', 'gear')},
            },
        ),
        migrations.CreateModel(
            name='CharacterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='characters.character')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.quality')),
            ],
            options={
                'unique_together': {('character', 'quality')},
            },
        ),
    ]
