# Generated by Django 5.0.1 on 2025-11-04 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeptPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Power point cost', max_digits=3)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplexForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(choices=[('device', 'Device'), ('file', 'File'), ('persona', 'Persona'), ('sprite', 'Sprite')], max_length=20)),
                ('duration', models.CharField(choices=[('instant', 'Instant (I)'), ('sustained', 'Sustained (S)'), ('permanent', 'Permanent (P)')], max_length=20)),
                ('fading', models.CharField(help_text='Fading value (e.g., L-1, L+2)', max_length=20)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('combat', 'Combat'), ('physical', 'Physical'), ('social', 'Social'), ('technical', 'Technical'), ('vehicle', 'Vehicle'), ('magical', 'Magical'), ('resonance', 'Resonance'), ('knowledge', 'Knowledge'), ('language', 'Language')], max_length=20)),
                ('linked_attribute', models.CharField(choices=[('body', 'Body'), ('agility', 'Agility'), ('reaction', 'Reaction'), ('strength', 'Strength'), ('charisma', 'Charisma'), ('intuition', 'Intuition'), ('logic', 'Logic'), ('willpower', 'Willpower'), ('magic', 'Magic'), ('resonance', 'Resonance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=True, help_text='Available for all characters')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('combat', 'Combat'), ('detection', 'Detection'), ('health', 'Health'), ('illusion', 'Illusion'), ('manipulation', 'Manipulation')], max_length=20)),
                ('spell_type', models.CharField(choices=[('physical', 'Physical'), ('mana', 'Mana')], max_length=20)),
                ('range_type', models.CharField(choices=[('touch', 'Touch (T)'), ('los', 'Line of Sight (LOS)'), ('los_area', 'Line of Sight (Area)')], max_length=20)),
                ('duration', models.CharField(choices=[('instant', 'Instant (I)'), ('sustained', 'Sustained (S)'), ('permanent', 'Permanent (P)')], max_length=20)),
                ('drain', models.CharField(help_text='Drain value (e.g., F-3, F-2, F+1)', max_length=20)),
                ('description', models.TextField()),
                ('is_default', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='distinguishing_features',
            field=models.TextField(blank=True, help_text='Scars, tattoos, cyberware, etc.'),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, help_text='e.g., 6\'2" or 188cm', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='lifestyle',
            field=models.CharField(choices=[('street', 'Street (0¥)'), ('squatter', 'Squatter (500¥)'), ('low', 'Low (2,000¥)'), ('medium', 'Medium (5,000¥)'), ('high', 'High (10,000¥)'), ('luxury', 'Luxury (100,000¥)')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='lifestyle_details',
            field=models.TextField(blank=True, help_text='Description of living situation'),
        ),
        migrations.AddField(
            model_name='character',
            name='notoriety',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='physical_damage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='public_awareness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='skin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='street_cred',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='stun_damage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 180 lbs or 82kg', max_length=50),
        ),
        migrations.AddField(
            model_name='gear',
            name='ammo',
            field=models.CharField(blank=True, help_text='e.g., 15(c), 30(c), 6(cy)', max_length=50),
        ),
        migrations.AddField(
            model_name='gear',
            name='armor_penetration',
            field=models.IntegerField(blank=True, help_text='AP value (negative number)', null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='armor_rating',
            field=models.IntegerField(blank=True, help_text='Armor value', null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='damage',
            field=models.CharField(blank=True, help_text='e.g., 8P, 6S, 10P', max_length=20),
        ),
        migrations.AddField(
            model_name='gear',
            name='firing_mode',
            field=models.CharField(blank=True, help_text='e.g., SS, SA, BF, FA', max_length=20),
        ),
        migrations.AddField(
            model_name='gear',
            name='recoil_compensation',
            field=models.IntegerField(blank=True, help_text='RC value', null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='weapon_range',
            field=models.CharField(blank=True, help_text='e.g., 0-5/6-20/21-40/41-60', max_length=50),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('archetype', models.CharField(blank=True, help_text='e.g., Fixer, Street Doc, Corporate Manager', max_length=100)),
                ('connection', models.IntegerField(help_text="Contact's influence and resources", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('loyalty', models.IntegerField(help_text="Contact's loyalty to character", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='characters.character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterAdeptPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adept_powers', to='characters.character')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.adeptpower')),
            ],
            options={
                'ordering': ['power__name'],
                'unique_together': {('character', 'power')},
            },
        ),
        migrations.CreateModel(
            name='CharacterComplexForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complex_forms', to='characters.character')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.complexform')),
            ],
            options={
                'ordering': ['form__name'],
                'unique_together': {('character', 'form')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Language name', max_length=100)),
                ('proficiency', models.CharField(choices=[('native', 'Native (N)'), ('fluent', 'Fluent'), ('conversational', 'Conversational'), ('basic', 'Basic')], default='conversational', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='characters.character')),
            ],
            options={
                'ordering': ['-proficiency', 'name'],
                'unique_together': {('character', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('specialization', models.CharField(blank=True, help_text='Optional specialization', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.skill')),
            ],
            options={
                'ordering': ['skill__category', 'skill__name'],
                'unique_together': {('character', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='characters.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.spell')),
            ],
            options={
                'ordering': ['spell__category', 'spell__name'],
                'unique_together': {('character', 'spell')},
            },
        ),
    ]
