# Generated by Django 5.0.1 on 2025-11-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_adeptpower_complexform_skill_spell_character_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_npc',
            field=models.BooleanField(default=False, help_text='Is this character an NPC (generated)'),
        ),
    ]
