# Generated by Django 5.0.1 on 2025-11-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_is_npc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='armor_bonus',
            field=models.IntegerField(default=0, help_text='Additional armor from cyberware/bioware'),
        ),
        migrations.AddField(
            model_name='gear',
            name='initiative_dice_bonus',
            field=models.IntegerField(default=0, help_text='Initiative dice bonus from augmentations'),
        ),
        migrations.AddField(
            model_name='gear',
            name='reaction_bonus',
            field=models.IntegerField(default=0, help_text='Reaction bonus from augmentations'),
        ),
    ]
