# Generated by Django 5.0.1 on 2025-11-11 10:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_adeptpower_complexform_skill_spell_character_age_and_more'),
        ('maps', '0002_alter_mapobject_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Campaign overview and description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Campaign start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Campaign end date (if completed)', null=True)),
                ('starting_karma', models.IntegerField(default=25, help_text='Starting karma for new characters', validators=[django.core.validators.MinValueValidator(0)])),
                ('starting_resources', models.IntegerField(default=50000, help_text='Starting nuyen for new characters', validators=[django.core.validators.MinValueValidator(0)])),
                ('gm_notes', models.TextField(blank=True, help_text='Private GM notes (not visible to players)')),
                ('player_notes', models.TextField(blank=True, help_text='Public campaign information visible to players')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, help_text='Characters participating in this campaign', related_name='campaigns', to='characters.character')),
                ('game_master', models.ForeignKey(help_text='The Game Master running this campaign', on_delete=django.db.models.deletion.CASCADE, related_name='gm_campaigns', to=settings.AUTH_USER_MODEL)),
                ('maps', models.ManyToManyField(blank=True, help_text='Maps used in this campaign', related_name='campaigns', to='maps.map')),
                ('players', models.ManyToManyField(blank=True, help_text='Players in this campaign', related_name='player_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Sequential session number', validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Session summary or adventure hook')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('actual_date', models.DateTimeField(blank=True, help_text='When the session actually occurred', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Session duration in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('gm_notes', models.TextField(blank=True, help_text='Private GM notes and preparation (not visible to players)')),
                ('session_notes', models.TextField(blank=True, help_text='Session recap and notes (visible to players)')),
                ('player_summary', models.TextField(blank=True, help_text='Player-written session summary')),
                ('karma_awarded', models.IntegerField(default=0, help_text='Karma awarded to characters this session', validators=[django.core.validators.MinValueValidator(0)])),
                ('nuyen_awarded', models.IntegerField(default=0, help_text='Nuyen awarded to characters this session', validators=[django.core.validators.MinValueValidator(0)])),
                ('encounters_faced', models.IntegerField(default=0, help_text='Number of combat encounters', validators=[django.core.validators.MinValueValidator(0)])),
                ('enemies_defeated', models.IntegerField(default=0, help_text='Total enemies defeated', validators=[django.core.validators.MinValueValidator(0)])),
                ('objectives_completed', models.TextField(blank=True, help_text='List of objectives completed (one per line)')),
                ('important_npcs', models.TextField(blank=True, help_text='Important NPCs encountered (one per line)')),
                ('loot_acquired', models.TextField(blank=True, help_text='Significant loot and rewards (one per line)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='campaigns.campaign')),
                ('characters_present', models.ManyToManyField(blank=True, help_text='Characters who participated in this session', related_name='sessions_attended', to='characters.character')),
                ('maps_used', models.ManyToManyField(blank=True, help_text='Maps used during this session', related_name='sessions', to='maps.map')),
            ],
            options={
                'ordering': ['campaign', 'session_number'],
                'unique_together': {('campaign', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='SessionObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='campaigns.session')),
            ],
            options={
                'ordering': ['is_completed', 'created_at'],
            },
        ),
    ]
