# Generated by Django 5.0.1 on 2025-11-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('characters', '0003_character_is_npc'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='npcs_involved',
            field=models.ManyToManyField(blank=True, help_text='NPCs encountered or involved in this session', limit_choices_to={'is_npc': True}, related_name='sessions_involved', to='characters.character'),
        ),
        migrations.AlterField(
            model_name='session',
            name='characters_present',
            field=models.ManyToManyField(blank=True, help_text='Player characters who participated in this session', limit_choices_to={'is_npc': False}, related_name='sessions_attended', to='characters.character'),
        ),
    ]
