# Generated by Django 5.0.1 on 2025-11-15 06:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_session_npcs_involved_and_more'),
        ('characters', '0003_character_is_npc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the encounter', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('current_round', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_turn', models.IntegerField(default=0, help_text="Index of current participant's turn")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(help_text='Session this encounter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='combat_encounters', to='campaigns.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CombatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('team', models.CharField(choices=[('player', 'Player Character'), ('ally', 'Ally/NPC'), ('enemy', 'Enemy'), ('neutral', 'Neutral')], default='enemy', max_length=20)),
                ('initiative', models.IntegerField(default=0, help_text='Initiative score (higher goes first)')),
                ('current_hp', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_hp', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('physical_damage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stun_damage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('edge_current', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('edge_max', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dodge_pool', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this participant still in combat?')),
                ('is_defeated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('map_x', models.IntegerField(blank=True, null=True)),
                ('map_y', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, help_text='Linked character (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.combatencounter')),
            ],
            options={
                'ordering': ['-initiative', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CombatEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('effect_type', models.CharField(choices=[('buff', 'Buff'), ('debuff', 'Debuff'), ('damage', 'Damage Over Time'), ('healing', 'Healing Over Time'), ('condition', 'Condition')], default='condition', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_rounds', models.IntegerField(default=1, help_text='How many rounds this effect lasts', validators=[django.core.validators.MinValueValidator(1)])),
                ('rounds_remaining', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('modifiers', models.JSONField(blank=True, default=dict, help_text="Stat modifiers (e.g., {'initiative': -2, 'armor': 4})")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='campaigns.combatparticipant')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
