# Generated by Django 5.0.1 on 2025-11-15 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_combatencounter_combatparticipant_combateffect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('combat_start', 'Combat Started'), ('combat_end', 'Combat Ended'), ('round_start', 'Round Started'), ('turn_start', 'Turn Started'), ('attack', 'Attack'), ('damage', 'Damage Taken'), ('healing', 'Healing Received'), ('effect_applied', 'Effect Applied'), ('effect_expired', 'Effect Expired'), ('movement', 'Movement'), ('defeated', 'Defeated'), ('revived', 'Revived'), ('edge_used', 'Edge Used'), ('other', 'Other Action')], help_text='Type of combat event', max_length=20)),
                ('round_number', models.IntegerField(help_text='Combat round when this event occurred', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(help_text='Human-readable description of the event')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional event data (damage, dice results, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Participant who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to='campaigns.combatparticipant')),
                ('encounter', models.ForeignKey(help_text='The combat encounter this log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='combat_logs', to='campaigns.combatencounter')),
                ('target', models.ForeignKey(blank=True, help_text='Participant who was targeted/affected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_received', to='campaigns.combatparticipant')),
            ],
            options={
                'ordering': ['encounter', 'timestamp'],
                'indexes': [models.Index(fields=['encounter', 'round_number'], name='campaigns_c_encount_0a167e_idx'), models.Index(fields=['encounter', 'event_type'], name='campaigns_c_encount_150f06_idx')],
            },
        ),
    ]
